version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/html
      - /var/www/html/docker
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/html
      - /var/www/html/docker
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    command: [nginx, '-g', 'daemon off;']

  database:
    container_name: loan-db
    build:
      context: ./database
    ports:
      - '3306:3306'
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=loan_db
      - MYSQL_USER=loan_user
      - MYSQL_PASSWORD=loan_pass
      - MYSQL_ROOT_PASSWORD=root_pass

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3307:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root_pass

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbitmq
  #   volumes:
  #       - ./rabbitmq/data/:/var/lib/rabbitmq/
  #       - ./rabbitmq/log/:/var/log/rabbitmq
  #   ports:
  #       - 5672:5672
  #       - 15672:15672